// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// / Default [FirebaseOptions] for use with your Firebase apps.
// /
// / Example:
// / ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB19kOHvVvYh-iqbSI6YHzkQrsnWwjVnuw',
    appId: '1:941775411349:web:231dab0a3bfabffb11e39c',
    messagingSenderId: '941775411349',
    projectId: 'study-buddy-d2130',
    authDomain: 'study-buddy-d2130.firebaseapp.com',
    storageBucket: 'study-buddy-d2130.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBppKqkmeCWh-mBNs-1VdqrmFN4QGATt-Q',
    appId: '1:941775411349:android:cc47a52f68bd5ebf11e39c',
    messagingSenderId: '941775411349',
    projectId: 'study-buddy-d2130',
    storageBucket: 'study-buddy-d2130.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4ukol26JqJRM6vXMObEiJ0wzWkAjt0ZY',
    appId: '1:941775411349:ios:cd8a4a5bac68daa211e39c',
    messagingSenderId: '941775411349',
    projectId: 'study-buddy-d2130',
    storageBucket: 'study-buddy-d2130.appspot.com',
    iosBundleId: 'com.example.studyBuddyFl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4ukol26JqJRM6vXMObEiJ0wzWkAjt0ZY',
    appId: '1:941775411349:ios:ce2d1754c939a53a11e39c',
    messagingSenderId: '941775411349',
    projectId: 'study-buddy-d2130',
    storageBucket: 'study-buddy-d2130.appspot.com',
    iosBundleId: 'com.example.studyBuddyFl.RunnerTests',
  );
}
